"""comments

Revision ID: 3cb5df1d1adb
Revises: 
Create Date: 2023-11-16 03:06:05.828499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cb5df1d1adb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorited',
    sa.Column('username', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_index(op.f('ix_favorited_username'), 'favorited', ['username'], unique=False)
    op.create_table('followings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_followings_id'), 'followings', ['id'], unique=False)
    op.create_table('tags',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articles',
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_table('association_table',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('following_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['following_id'], ['followings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'following_id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('article_slug', sa.String(), nullable=False),
    sa.Column('author', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_slug'], ['articles.slug'], ),
    sa.ForeignKeyConstraint(['author'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'article_slug')
    )
    op.create_table('favorite_association',
    sa.Column('article_slug', sa.String(), nullable=False),
    sa.Column('favorited_by_user', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['article_slug'], ['articles.slug'], ),
    sa.ForeignKeyConstraint(['favorited_by_user'], ['favorited.username'], ),
    sa.PrimaryKeyConstraint('article_slug', 'favorited_by_user')
    )
    op.create_table('tags_article',
    sa.Column('article_slug', sa.String(), nullable=False),
    sa.Column('tag_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['article_slug'], ['articles.slug'], ),
    sa.ForeignKeyConstraint(['tag_name'], ['tags.name'], ),
    sa.PrimaryKeyConstraint('article_slug', 'tag_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags_article')
    op.drop_table('favorite_association')
    op.drop_table('comments')
    op.drop_table('association_table')
    op.drop_table('articles')
    op.drop_table('users')
    op.drop_table('tags')
    op.drop_index(op.f('ix_followings_id'), table_name='followings')
    op.drop_table('followings')
    op.drop_index(op.f('ix_favorited_username'), table_name='favorited')
    op.drop_table('favorited')
    # ### end Alembic commands ###
