"""favorites

Revision ID: 548122cca7a5
Revises: 7d0d7b56effd
Create Date: 2023-11-09 01:06:25.309297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '548122cca7a5'
down_revision: Union[str, None] = '7d0d7b56effd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorited',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favorited_id'), 'favorited', ['id'], unique=False)
    op.create_table('favorite_association',
    sa.Column('article_slug', sa.String(), nullable=False),
    sa.Column('favorited_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_slug'], ['articles.slug'], ),
    sa.ForeignKeyConstraint(['favorited_id'], ['favorited.id'], ),
    sa.PrimaryKeyConstraint('article_slug', 'favorited_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_association')
    op.drop_index(op.f('ix_favorited_id'), table_name='favorited')
    op.drop_table('favorited')
    # ### end Alembic commands ###
