"""remove comments

Revision ID: 60dfa14f76b1
Revises: 70b0d2960163
Create Date: 2023-11-15 03:47:12.777398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60dfa14f76b1'
down_revision: Union[str, None] = '70b0d2960163'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_association')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_association',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(), nullable=False),
    sa.Column('article_slug', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['article_slug'], ['articles.slug'], ),
    sa.PrimaryKeyConstraint('id', 'article_slug')
    )
    # ### end Alembic commands ###
